name 'vagrant_compat'
maintainer 'Sayantam Dey'
maintainer_email 'sayantam.dey@3pillarglobal.com'
license 'all_rights'
description 'Installs/Configures etc-environment'
long_description 'Installs/Configures etc-environment'
version '0.1.0'
