name 'oracle_java_8'
maintainer 'Sayantam Dey'
maintainer_email 'sayantam.dey@3pillarglobal.com'
license 'all_rights'
description 'Installs/Configures oracle_java_8'
long_description 'Installs/Configures oracle_java_8'
version '0.1.0'
