name 'etc-environment'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures etc-environment'
long_description 'Installs/Configures etc-environment'
version '0.1.0'
